pipelineType: java
buildTool: Maven
repositoryTool: Nexus
checkoutCredentialId: "Github Token"
sonarRunner: SonarQube_Scanner_2.8
sonarServer: mysonarserver
resources:
  - name: repositoryConfig
    path: artifactory_config.yaml
    type: yaml
  - name: buildConfig
    path: build_config.json
    type: json
  - name: deployConfig
    path: deploy_config.yaml
    type: yaml
tools:
  - name: jdk
    value: jdk-1.8
  - name: maven
    value: maven-3.3.9
  - name: sonar
    value: SonarQube_Scanner_2.8
stages:
  - name: "Initialize Pipeline"
    tasks:
      - type: task
        name: loadMetadata
  - name: Build
    tasks:
      - type: task
        name: mavenBuildTask
  - name: "Upload Artifacts"
    tasks:
      - type: task
        name: uploadArtifactTask
  - name: "Scan Code"
    tasks:
      - type: task
        name: sonarTask
  - name: "Deploy"
    tasks:
      - type: task
        name: deployTask
        label: dev
  - name: "Deploy to SIT"
    tasks:
      - type: task
        name: deployTask
        label: sit
