pipelineType: java
buildTool: Maven
repositoryTool: Nexus
checkoutCredentialId: "Github Token"
sonarRunner: SonarQube_Scanner_2.8
sonarServer: mysonarserver
tools:
  - name: jdk
    value: jdk-1.8
  - name: maven
    value: maven-3.3.9
  - name: sonar
    value: SonarQube_Scanner_2.8
runTests: true
runScans: false
stages:
  stage:
    name: "Initialize Pipeline"
    tasks:
      task: loadMetadata
  stage:
    name: Build
    tasks:
      task: mavenBuildTask
  stage:
    name: "Upload Artifacts"
    tasks:
      task: uploadArtifactTask
  stage:
    name: "Scan Code"
    tasks:
      task: sonarTask


